version: "3.7"

services:
  bitcoin:
    container_name: bitcoin
    restart: on-failure
    build:
      context: ./bitcoin
      dockerfile: Dockerfile
    volumes:
      - ${DIR}/bitcoin:/data/.bitcoin
    networks:
      default:

  lnd:
    container_name: lnd
    restart: on-failure
    build:
      context: ./lnd
      dockerfile: Dockerfile
    depends_on: [bitcoin]
    volumes:
      - ${DIR}/lnd:/data/.lnd
    networks:
      default:

networks:
  default:
    name: deco_main_network
