version: "3.7"

services:
  bitcoin:
    container_name: bitcoin
    restart: on-failure
    image: lncm/bitcoind:v22.0
    volumes:
      - ${DIR}/bitcoin:/data/.bitcoin
    ports:
      - "$BITCOIN_P2P_PORT:$BITCOIN_P2P_PORT"
    networks:
      default:
        ipv4_address: $BITCOIN_IP

  lnd:
    container_name: lnd
    restart: on-failure
    image: lightninglabs/lnd:v0.13.1-beta
    depends_on: [bitcoin]
    user: 1000:1000
    ports:
      - "9735:9735"
      - "$LND_REST_PORT:$LND_REST_PORT"
      - "$LND_GRPC_PORT:$LND_GRPC_PORT"
    environment:
      HOME: /data
    volumes:
      - ${DIR}/lnd:/data/.lnd
    networks:
      default:
        ipv4_address: $LND_IP

networks:
  default:
    name: deco_main_network
    ipam:
      driver: default
      config:
        - subnet: "${NETWORK_IP}/24"
