version: "3.7"

services:
  bitcoin:
    container_name: bitcoin
    restart: on-failure
    image: lncm/bitcoind:v22.0
    volumes:
      - ${DIR}/bitcoin:/data/.bitcoin
    ports:
      - 8080:8080
    networks:
      default:
        ipv4_address: $BITCOIN_IP

  lnd:
    container_name: lnd
    restart: on-failure
    image: lightninglabs/lnd:v0.13.1-beta
    depends_on: [bitcoin]
    volumes:
      - ${DIR}/lnd:/data/.lnd
    networks:
      default:
        ipv4_address: $LND_IP

networks:
  default:
    name: deco_main_network
    ipam:
      driver: default
      config:
        - subnet: "${NETWORK_IP}/24"
