version: "3.7"

services:
  bitcoin:
    container_name: bitcoin
    restart: on-failure
    build:
      context: ./bitcoin
      dockerfile: Dockerfile
    volumes:
      - ./bitcoin:/bitcoin/.bitcoin
    networks:
      default:

  lnd:
    container_name: lnd
    restart: on-failure
    image: lightninglabs/lnd:v0.12.0-beta
    depends_on: [bitcoin]
    volumes:
      - ./lnd:/root/.lnd
    networks:
      default:

networks:
  default:
    name: deco_main_network
