version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:6.2-buster
    command: redis-server --requirepass $APP_REDIS_PASSWORD
    restart: on-failure
    stop_grace_period: 1m
    stop_signal: SIGINT
    ports:
      - '${APP_REDIS_PORT}:${APP_REDIS_PORT}'
    volumes:
      - ./data/redis:/data
    networks:
      default:
        ipv4_address: $APP_REDIS_IP
  decolnd:
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app/
    container_name: decolnd
    restart: unless-stopped
    ports:
      - '${APP_PORT}:${APP_PORT}'
    build:
      dockerfile: Dockerfile
      context: ./
    networks:
      default:
        ipv4_address: $APP_IP

networks:
  default:
    name: deco_network
    ipam:
      driver: default
      config:
        - subnet: '$NETWORK_IP/24'
