version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DBNAME}
  decolnd:
    env_file:
      - .env
    volumes:
      # - /usr/src/app/node_modules
      - .:/usr/src/app/
    container_name: decolnd
    restart: unless-stopped
    ports:
      - '${APP_PORT}:${APP_PORT}'
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - postgres
